name: Build and Test

on: [push, pull_request]

jobs:

  test-windows-x64:
    runs-on: windows-latest
    steps:
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          7.0.x
    - run: dotnet --info
    - uses: actions/checkout@v3
    - name: Test (.NET 7.0/Debug)
      run: dotnet test -f net7.0 -c Debug
    - name: Test (.NET 7.0/Release)
      run: dotnet test -f net7.0 -c Release
    - name: Test (.NET 6.0/Debug)
      run: dotnet test -f net6.0 -c Debug
    - name: Test (.NET 6.0/Release)
      run: dotnet test -f net6.0 -c Release
    - name: Pack
      run: dotnet pack -c Release
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: '**/*.nupkg'

  test-ubuntu-x64:
    runs-on: ubuntu-latest
    steps:
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          7.0.x
    - run: dotnet --info
    - uses: actions/checkout@v3
    - name: Test (.NET 7.0/Debug)
      run: dotnet test -f net7.0 -c Debug
    - name: Test (.NET 7.0/Release)
      run: dotnet test -f net7.0 -c Release
    - name: Test (.NET 6.0/Debug)
      run: dotnet test -f net6.0 -c Debug
    - name: Test (.NET 6.0/Release)
      run: dotnet test -f net6.0 -c Release

  test-alpine-x64:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:7.0-alpine
    steps:
    - run: dotnet --info
    - uses: actions/checkout@v3
    - name: Test (.NET 7.0/Debug)
      run: dotnet test -f net7.0 -c Debug
    - name: Test (.NET 7.0/Release)
      run: dotnet test -f net7.0 -c Release

  test-macos-x64:
    runs-on: macos-latest
    steps:
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          7.0.x
    - run: dotnet --info
    - uses: actions/checkout@v3
    - name: Test (.NET 7.0/Debug)
      run: dotnet test -f net7.0 -c Debug
    - name: Test (.NET 7.0/Release)
      run: dotnet test -f net7.0 -c Release
    - name: Test (.NET 6.0/Debug)
      run: dotnet test -f net6.0 -c Debug
    - name: Test (.NET 6.0/Release)
      run: dotnet test -f net6.0 -c Release
